<?php
/**
 *  @author: Lorenzo Salvadorini aka LoreLLo <lorello@openweb.it>
 */
$labels = array();
$labels['listcommands_mailinglist'] = 'Mailing List';
$labels['listcommands_help'] = 'Chiedi aiuto';
$labels['listcommands_subscribe'] = 'Iscritivi';
$labels['listcommands_unsubscribe'] = 'Cancellati';
$labels['listcommands_post'] = 'Invia un messaggio alla lista';
$labels['listcommands_admin'] = 'Contatta l\'amministratore';
$labels['listcommands_archive'] = 'Apri l\'archivio';

?>
